# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msgs_record/glosa.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class glosa(genpy.Message):
  _md5sum = "e8951b090850cccee9e623b752294b0d"
  _type = "msgs_record/glosa"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """uint8 RED = 3
uint8 GREEN = 5
uint8 YELLOW = 7
uint8 NEW_TARGET = 1
uint8 UPDATE_TARGET = 3
uint8 COASTED_TARGET = 4

std_msgs/Header header

float64 latitude
float64 longitude
float64 height
float64 Utmx
float64 Utmy
float64 Yaw
float64 EgoSpeed

uint16 stationId
float64 SpeedLimit
float64 dis2inter

uint8 Str_is_val
uint8 StrSignalState
float64 StrlikelyEndTime

uint8 Left_is_val
uint8 LeftSignalState
float64 LeftlikelyEndTime

uint8 Right_is_val
uint8 RighSignalState
float64 RightlikelyEndTime

float64 azimuth
float64 distance
float64 speed
uint8 status
uint8 id

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  # Pseudo-constants
  RED = 3
  GREEN = 5
  YELLOW = 7
  NEW_TARGET = 1
  UPDATE_TARGET = 3
  COASTED_TARGET = 4

  __slots__ = ['header','latitude','longitude','height','Utmx','Utmy','Yaw','EgoSpeed','stationId','SpeedLimit','dis2inter','Str_is_val','StrSignalState','StrlikelyEndTime','Left_is_val','LeftSignalState','LeftlikelyEndTime','Right_is_val','RighSignalState','RightlikelyEndTime','azimuth','distance','speed','status','id']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','uint16','float64','float64','uint8','uint8','float64','uint8','uint8','float64','uint8','uint8','float64','float64','float64','float64','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,latitude,longitude,height,Utmx,Utmy,Yaw,EgoSpeed,stationId,SpeedLimit,dis2inter,Str_is_val,StrSignalState,StrlikelyEndTime,Left_is_val,LeftSignalState,LeftlikelyEndTime,Right_is_val,RighSignalState,RightlikelyEndTime,azimuth,distance,speed,status,id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(glosa, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.height is None:
        self.height = 0.
      if self.Utmx is None:
        self.Utmx = 0.
      if self.Utmy is None:
        self.Utmy = 0.
      if self.Yaw is None:
        self.Yaw = 0.
      if self.EgoSpeed is None:
        self.EgoSpeed = 0.
      if self.stationId is None:
        self.stationId = 0
      if self.SpeedLimit is None:
        self.SpeedLimit = 0.
      if self.dis2inter is None:
        self.dis2inter = 0.
      if self.Str_is_val is None:
        self.Str_is_val = 0
      if self.StrSignalState is None:
        self.StrSignalState = 0
      if self.StrlikelyEndTime is None:
        self.StrlikelyEndTime = 0.
      if self.Left_is_val is None:
        self.Left_is_val = 0
      if self.LeftSignalState is None:
        self.LeftSignalState = 0
      if self.LeftlikelyEndTime is None:
        self.LeftlikelyEndTime = 0.
      if self.Right_is_val is None:
        self.Right_is_val = 0
      if self.RighSignalState is None:
        self.RighSignalState = 0
      if self.RightlikelyEndTime is None:
        self.RightlikelyEndTime = 0.
      if self.azimuth is None:
        self.azimuth = 0.
      if self.distance is None:
        self.distance = 0.
      if self.speed is None:
        self.speed = 0.
      if self.status is None:
        self.status = 0
      if self.id is None:
        self.id = 0
    else:
      self.header = std_msgs.msg.Header()
      self.latitude = 0.
      self.longitude = 0.
      self.height = 0.
      self.Utmx = 0.
      self.Utmy = 0.
      self.Yaw = 0.
      self.EgoSpeed = 0.
      self.stationId = 0
      self.SpeedLimit = 0.
      self.dis2inter = 0.
      self.Str_is_val = 0
      self.StrSignalState = 0
      self.StrlikelyEndTime = 0.
      self.Left_is_val = 0
      self.LeftSignalState = 0
      self.LeftlikelyEndTime = 0.
      self.Right_is_val = 0
      self.RighSignalState = 0
      self.RightlikelyEndTime = 0.
      self.azimuth = 0.
      self.distance = 0.
      self.speed = 0.
      self.status = 0
      self.id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7dH2d2Bd2Bd2B4d2B().pack(_x.latitude, _x.longitude, _x.height, _x.Utmx, _x.Utmy, _x.Yaw, _x.EgoSpeed, _x.stationId, _x.SpeedLimit, _x.dis2inter, _x.Str_is_val, _x.StrSignalState, _x.StrlikelyEndTime, _x.Left_is_val, _x.LeftSignalState, _x.LeftlikelyEndTime, _x.Right_is_val, _x.RighSignalState, _x.RightlikelyEndTime, _x.azimuth, _x.distance, _x.speed, _x.status, _x.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 130
      (_x.latitude, _x.longitude, _x.height, _x.Utmx, _x.Utmy, _x.Yaw, _x.EgoSpeed, _x.stationId, _x.SpeedLimit, _x.dis2inter, _x.Str_is_val, _x.StrSignalState, _x.StrlikelyEndTime, _x.Left_is_val, _x.LeftSignalState, _x.LeftlikelyEndTime, _x.Right_is_val, _x.RighSignalState, _x.RightlikelyEndTime, _x.azimuth, _x.distance, _x.speed, _x.status, _x.id,) = _get_struct_7dH2d2Bd2Bd2B4d2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7dH2d2Bd2Bd2B4d2B().pack(_x.latitude, _x.longitude, _x.height, _x.Utmx, _x.Utmy, _x.Yaw, _x.EgoSpeed, _x.stationId, _x.SpeedLimit, _x.dis2inter, _x.Str_is_val, _x.StrSignalState, _x.StrlikelyEndTime, _x.Left_is_val, _x.LeftSignalState, _x.LeftlikelyEndTime, _x.Right_is_val, _x.RighSignalState, _x.RightlikelyEndTime, _x.azimuth, _x.distance, _x.speed, _x.status, _x.id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 130
      (_x.latitude, _x.longitude, _x.height, _x.Utmx, _x.Utmy, _x.Yaw, _x.EgoSpeed, _x.stationId, _x.SpeedLimit, _x.dis2inter, _x.Str_is_val, _x.StrSignalState, _x.StrlikelyEndTime, _x.Left_is_val, _x.LeftSignalState, _x.LeftlikelyEndTime, _x.Right_is_val, _x.RighSignalState, _x.RightlikelyEndTime, _x.azimuth, _x.distance, _x.speed, _x.status, _x.id,) = _get_struct_7dH2d2Bd2Bd2B4d2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7dH2d2Bd2Bd2B4d2B = None
def _get_struct_7dH2d2Bd2Bd2B4d2B():
    global _struct_7dH2d2Bd2Bd2B4d2B
    if _struct_7dH2d2Bd2Bd2B4d2B is None:
        _struct_7dH2d2Bd2Bd2B4d2B = struct.Struct("<7dH2d2Bd2Bd2B4d2B")
    return _struct_7dH2d2Bd2Bd2B4d2B
