(cl:defpackage gps_msgs-msg
  (:use )
  (:export
   "<CARRIER>"
   "CARRIER"
   "<DELTAPOSITION>"
   "DELTAPOSITION"
   "<ENURPVDATA>"
   "ENURPVDATA"
   "<EPHEMERIS>"
   "EPHEMERIS"
   "<GPSRANGE>"
   "GPSRANGE"
   "<INSPVAX>"
   "INSPVAX"
   "<L1L2RANGE>"
   "L1L2RANGE"
   "<L1RANGE>"
   "L1RANGE"
   "<RPV>"
   "RPV"
   "<RPVDATA>"
   "RPVDATA"
   "<RPVSTATUS>"
   "RPVSTATUS"
   "<SATELLITE>"
   "SATELLITE"
   "<SATELLITES>"
   "SATELLITES"
   "<UTM>"
   "UTM"
   "<XYZRPVDATA>"
   "XYZRPVDATA"
   "<GPSUTM>"
   "GPSUTM"
  ))

