(cl:in-package v2x-msg)
(cl:export '(HEADER-VAL
          HEADER
          STATIONID-VAL
          STATIONID
          SPEEDLIMIT-VAL
          SPEEDLIMIT
          DIS2INTER-VAL
          DIS2INTER
          STR_IS_VAL-VAL
          STR_IS_VAL
          STRSIGNALSTATE-VAL
          STRSIGNALSTATE
          STRLIKELYENDTIME-VAL
          STRLIKELYENDTIME
          LEFT_IS_VAL-VAL
          LEFT_IS_VAL
          LEFTSIGNALSTATE-VAL
          LEFTSIGNALSTATE
          LEFTLIKELYENDTIME-VAL
          LEFTLIKELYENDTIME
          RIGHT_IS_VAL-VAL
          RIGHT_IS_VAL
          RIGHSIGNALSTATE-VAL
          RIGHSIGNALSTATE
          RIGHTLIKELYENDTIME-VAL
          RIGHTLIKELYENDTIME
))