// Generated by gencpp from file can_msgs/Frame.msg
// DO NOT EDIT!


#ifndef CAN_MSGS_MESSAGE_FRAME_H
#define CAN_MSGS_MESSAGE_FRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace can_msgs
{
template <class ContainerAllocator>
struct Frame_
{
  typedef Frame_<ContainerAllocator> Type;

  Frame_()
    : id(0)
    , is_rtr(false)
    , is_extended(false)
    , is_error(false)
    , len(0)
    , data()  {
      data.assign(0);
  }
  Frame_(const ContainerAllocator& _alloc)
    : id(0)
    , is_rtr(false)
    , is_extended(false)
    , is_error(false)
    , len(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _is_rtr_type;
  _is_rtr_type is_rtr;

   typedef uint8_t _is_extended_type;
  _is_extended_type is_extended;

   typedef uint8_t _is_error_type;
  _is_error_type is_error;

   typedef uint8_t _len_type;
  _len_type len;

   typedef boost::array<uint8_t, 8>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::can_msgs::Frame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_msgs::Frame_<ContainerAllocator> const> ConstPtr;

}; // struct Frame_

typedef ::can_msgs::Frame_<std::allocator<void> > Frame;

typedef boost::shared_ptr< ::can_msgs::Frame > FramePtr;
typedef boost::shared_ptr< ::can_msgs::Frame const> FrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_msgs::Frame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_msgs::Frame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'can_msgs': ['/home/chenhao/catkin_ws/src/can_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Frame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Frame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Frame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Frame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Frame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Frame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_msgs::Frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cb4169590eea9366f0510af7121fabe";
  }

  static const char* value(const ::can_msgs::Frame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cb4169590eea936ULL;
  static const uint64_t static_value2 = 0x6f0510af7121fabeULL;
};

template<class ContainerAllocator>
struct DataType< ::can_msgs::Frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_msgs/Frame";
  }

  static const char* value(const ::can_msgs::Frame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_msgs::Frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n\
bool is_rtr\n\
bool is_extended\n\
bool is_error\n\
uint8 len\n\
uint8[8] data\n\
\n\
";
  }

  static const char* value(const ::can_msgs::Frame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_msgs::Frame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.is_rtr);
      stream.next(m.is_extended);
      stream.next(m.is_error);
      stream.next(m.len);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Frame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_msgs::Frame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_msgs::Frame_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "is_rtr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_rtr);
    s << indent << "is_extended: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_extended);
    s << indent << "is_error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_error);
    s << indent << "len: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.len);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MSGS_MESSAGE_FRAME_H
