(cl:in-package glosa-msg)
(cl:export '(EGOSPEED-VAL
          EGOSPEED
          PRESPEED-VAL
          PRESPEED
          LIMITSPEED-VAL
          LIMITSPEED
          DIS2STOPLINE-VAL
          DIS2STOPLINE
          INTERSECTIONID-VAL
          INTERSECTIONID
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          UPPERSPEED-VAL
          UPPERSPEED
          BOTTOMSPEED-VAL
          BOTTOMSPEED
          KEEPCURSPEED-VAL
          KEEPCURSPEED
          STR_IS_VAL-VAL
          STR_IS_VAL
          STRCOLOR-VAL
          STRCOLOR
          STRLIKELYENDTIME-VAL
          STRLIKELYENDTIME
          LEFT_IS_VAL-VAL
          LEFT_IS_VAL
          LEFTCOLOR-VAL
          LEFTCOLOR
          LEFTLIKELYENDTIME-VAL
          LEFTLIKELYENDTIME
          RIGHT_IS_VAL-VAL
          RIGHT_IS_VAL
          RIGHTCOLOR-VAL
          RIGHTCOLOR
          RIGHTLIKELYENDTIME-VAL
          RIGHTLIKELYENDTIME
))