# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from can_msgs/Frame.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Frame(genpy.Message):
  _md5sum = "4cb4169590eea9366f0510af7121fabe"
  _type = "can_msgs/Frame"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 id
bool is_rtr
bool is_extended
bool is_error
uint8 len
uint8[8] data

"""
  __slots__ = ['id','is_rtr','is_extended','is_error','len','data']
  _slot_types = ['uint32','bool','bool','bool','uint8','uint8[8]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,is_rtr,is_extended,is_error,len,data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Frame, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.is_rtr is None:
        self.is_rtr = False
      if self.is_extended is None:
        self.is_extended = False
      if self.is_error is None:
        self.is_error = False
      if self.len is None:
        self.len = 0
      if self.data is None:
        self.data = b'\0'*8
    else:
      self.id = 0
      self.is_rtr = False
      self.is_extended = False
      self.is_error = False
      self.len = 0
      self.data = b'\0'*8

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I4B().pack(_x.id, _x.is_rtr, _x.is_extended, _x.is_error, _x.len))
      _x = self.data
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_8B().pack(*_x))
      else:
        buff.write(_get_struct_8s().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.id, _x.is_rtr, _x.is_extended, _x.is_error, _x.len,) = _get_struct_I4B().unpack(str[start:end])
      self.is_rtr = bool(self.is_rtr)
      self.is_extended = bool(self.is_extended)
      self.is_error = bool(self.is_error)
      start = end
      end += 8
      self.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I4B().pack(_x.id, _x.is_rtr, _x.is_extended, _x.is_error, _x.len))
      _x = self.data
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_8B().pack(*_x))
      else:
        buff.write(_get_struct_8s().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.id, _x.is_rtr, _x.is_extended, _x.is_error, _x.len,) = _get_struct_I4B().unpack(str[start:end])
      self.is_rtr = bool(self.is_rtr)
      self.is_extended = bool(self.is_extended)
      self.is_error = bool(self.is_error)
      start = end
      end += 8
      self.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
_struct_8s = None
def _get_struct_8s():
    global _struct_8s
    if _struct_8s is None:
        _struct_8s = struct.Struct("<8s")
    return _struct_8s
_struct_I4B = None
def _get_struct_I4B():
    global _struct_I4B
    if _struct_I4B is None:
        _struct_I4B = struct.Struct("<I4B")
    return _struct_I4B
