(cl:in-package msgs_record-msg)
(cl:export '(HEADER-VAL
          HEADER
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          UTMX-VAL
          UTMX
          UTMY-VAL
          UTMY
          YAW-VAL
          YAW
          EGOSPEED-VAL
          EGOSPEED
          STATIONID-VAL
          STATIONID
          SPEEDLIMIT-VAL
          SPEEDLIMIT
          DIS2INTER-VAL
          DIS2INTER
          STR_IS_VAL-VAL
          STR_IS_VAL
          STRSIGNALSTATE-VAL
          STRSIGNALSTATE
          STRLIKELYENDTIME-VAL
          STRLIKELYENDTIME
          LEFT_IS_VAL-VAL
          LEFT_IS_VAL
          LEFTSIGNALSTATE-VAL
          LEFTSIGNALSTATE
          LEFTLIKELYENDTIME-VAL
          LEFTLIKELYENDTIME
          RIGHT_IS_VAL-VAL
          RIGHT_IS_VAL
          RIGHSIGNALSTATE-VAL
          RIGHSIGNALSTATE
          RIGHTLIKELYENDTIME-VAL
          RIGHTLIKELYENDTIME
          AZIMUTH-VAL
          AZIMUTH
          DISTANCE-VAL
          DISTANCE
          SPEED-VAL
          SPEED
          STATUS-VAL
          STATUS
          ID-VAL
          ID
))